CREATE TABLE Admin (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Benutzername TEXT NOT NULL,
	Passwort TEXT NOT NULL
);


CREATE TABLE Person (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Anrede INTEGER NOT NULL,
	Vorname TEXT NOT NULL,
	Nachname TEXT NOT NULL,
	AdresseID INTEGER NOT NULL,
	Telefonnummer TEXT NOT NULL,
	Email TEXT NOT NULL,
	CONSTRAINT fk_Person1 FOREIGN KEY (AdresseID) REFERENCES Adresse(ID)
);

CREATE TABLE Adresse (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Strasse TEXT NOT NULL,
	PLZ TEXT NOT NULL,
	Ort TEXT NOT NULL
);


CREATE TABLE Umzug (
	ID Integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	Umzugsdatum TEXT NOT NULL,
	Entfernung NUMERIC NOT NULL,
	PersonID INTEGER NOT NULL,
	CONSTRAINT fk_PersonU FOREIGN KEY (PersonID) REFERENCES Person(ID)
);

CREATE TABLE Packungen ( 
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Bezeichnung TEXT NOT NULL
);

CREATE TABLE Umzug_Packung (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	UmzugID INTEGER NOT NULL,
	PackungenID INTEGER NOT NULL,
	Menge INTEGER NOT NULL,
	CONSTRAINT fk_UP1 FOREIGN KEY (UmzugID) REFERENCES Umzug(ID),
	CONSTRAINT fk_UP2 FOREIGN KEY (PackungenID) REFERENCES Packungen(ID)
);
